### PR TITLE
feat: add dockerfile

### PR DESCRIPTION
**Pull request by georgettica**
related to #13

### CODE REVIEW

**Review by saptarsi96 — APPROVED** [review]
Looks Good! Can you please send a screenshot of the application after docker-up whereby we can open the jupyter notebooks in the browser itself hassle-free?

**Comment by georgettica** [comment]
Will do that, and update when I'm done :)

**Comment by saptarsi96** [comment]
@benhills You can merge this change to make this application "Dockerizable". Will update the Readme.md accordingly.

**Comment by georgettica** [comment]
done, see this now and you should be able to see the picture

**Review by saptarsi96 — APPROVED** [review]
Great Job! @georgettica

**Comment by georgettica** [comment]
Could you add the hacktoberfest thing to this issue?

**Comment by saptarsi96** [comment]
Sure! @benhills Can you please add the required label to this issue?

**Comment by georgettica** [comment]
@benhills, any update?

**Comment by benhills** [comment]
Hey, yeah there shouldn't be any big problem with this. The science team is meeting tomorrow and I will bring this up. It seems likely at this point that we are moving this repository into the larger framework of icepyx. Any future development is likely going to be done there. If you two are interested in this project, you should check out that repository. There is a ton of work being done there and many places where you could plug in.

**Comment by georgettica** [comment]
can you plug the repo url here?

**Comment by benhills** [comment]
https://github.com/icesat2py/icepyx
I will probably be moving this work onto a branch of that repo later this week.

**Review by benhills — COMMENTED** [review]
This looks good. As I said in the other PR, I am not sure that we need this at the moment. We will come back to this PR when we are further along.

**Comment by georgettica** [comment]
@benhills if you need a hand, remeber you can always ping me :)

**Comment by georgettica** [comment]
I see it's still open.. any traction / help from my side?

**Comment by georgettica** [comment]
Sadly closing due to inactivity.. I will keep the branch open if you ever need this

**Pull request closed without merging**
